# Generated by Django 3.2.4 on 2021-06-08 21:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
