# Generated by Django 3.2.4 on 2021-06-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_user_profilepicid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicId',
            field=models.UUIDField(null=True),
        ),
    ]
